name: Publish

on:
  push:
    branches:
    - main

concurrency: ${{ github.workflow }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        mod: ['transmission-nat-pmp']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: moritzchow318
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ${{ matrix.mod }}/Dockerfile
        context: ${{ matrix.mod }}
        tags: moritzchow318/docker-mods:transmission-nat-pmp
        platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
        push: true
